create or replace PACKAGE PAC_SVODKA AS 

type r_UGH_REPORT_Svodka is record(
REPORTORDER_SVODKA	VARCHAR2(10),
PLAN	NUMBER,
SHOVID	VARCHAR2(30),
TASKDATE	DATE,
WORKTIME_1	NUMBER,
VOLUMETOTAL_1	NUMBER,
AREA_1	VARCHAR2(4000),
WORKTIME_2	NUMBER,
VOLUMETOTAL_2	NUMBER,
AREA_2	VARCHAR2(4000),
VOLUMETOTAL_D	NUMBER,
WORKTIME_D	NUMBER,
TECHSTOP	NUMBER,
TECHNOLOGSTOP	NUMBER,
ORGSTOP	NUMBER,
READYGTTSTOP	NUMBER,
OTHERSTOP	NUMBER,
ETO	NUMBER,
PPR_AND_TO	NUMBER,
KTG	NUMBER,
KIO	NUMBER,
STOPPAGE_1	VARCHAR2(4000 CHAR),
STOPPAGE_2	VARCHAR2(4000 CHAR)
);

END PAC_SVODKA;


