
  CREATE OR REPLACE FORCE VIEW "UGH"."V_PARAMETERS" ("PARAMNAME", "PARAMTYPE", "STRINGVALUE", "NUMVALUE") AS 
  SELECT 
    "PARAMNAME","PARAMTYPE","STRINGVALUE","NUMVALUE"
FROM dispatcher.parameters;
