
  CREATE OR REPLACE FORCE VIEW "UGH"."V_WELLS_NOW" ("BLOCK_NAME", "RIGNAME", "MESTIME", "WELLNUMBER") AS 
  SELECT 
    "BLOCK_NAME","RIGNAME","MESTIME","WELLNUMBER"
FROM 
    
ugh.v_wells_now@rigs;
