
  CREATE OR REPLACE FORCE VIEW "UGH"."V_SHIFTREPORTSADV_MONTH" ("VEHID", "TASKDATE", "SHIFT", "SHOVID", "UNLOADID", "LOADTYPE", "WORKTYPE", "AVLENGTH", "ROUTELENGTH", "LENGTHMANUAL", "WEIGHTSENSOR", "GPSSENSOR", "TRIPNUMBERAUTO", "TRIPNUMBERMANUAL", "AVWEIGHT", "MAXWEIGHT", "MINWEIGHT", "WEIGHTRATE", "VOLUMERATE", "SPECIFICFUELRATE", "ISEDITED", "ISLASTROUTE", "MASH_SMEN", "AREA", "WORK_TIME_MANUAL", "WORK_TIME_AUTO", "INSERTTIME", "UPDATETIME", "UPDATESNUM", "AVWEIGHTONINSERT", "CUSTOMERNAME", "DANGERLEVEL", "KVDR_CODE", "LOADHEIGHT", "UNLOADHEIGHT", "STOPTIME", "REPAIRTIME", "REPAIR_IS_TO", "UNLOADIDFORLOAD", "ALLLENGTH", "REPORTSHIFT", "REPORTDATE", "AVHEIGHT", "AVGXLOAD", "AVGYLOAD", "WEIGHT") AS 
  select "VEHID","TASKDATE","SHIFT","SHOVID","UNLOADID","LOADTYPE","WORKTYPE","AVLENGTH",
"ROUTELENGTH","LENGTHMANUAL","WEIGHTSENSOR","GPSSENSOR","TRIPNUMBERAUTO",
"TRIPNUMBERMANUAL","AVWEIGHT","MAXWEIGHT","MINWEIGHT","WEIGHTRATE","VOLUMERATE",
"SPECIFICFUELRATE","ISEDITED","ISLASTROUTE","MASH_SMEN","AREA","WORK_TIME_MANUAL",
"WORK_TIME_AUTO","INSERTTIME","UPDATETIME","UPDATESNUM","AVWEIGHTONINSERT",
"CUSTOMERNAME","DANGERLEVEL","KVDR_CODE","LOADHEIGHT","UNLOADHEIGHT","STOPTIME",
"REPAIRTIME","REPAIR_IS_TO","UNLOADIDFORLOAD","ALLLENGTH","REPORTSHIFT","REPORTDATE",
"AVHEIGHT","AVGXLOAD","AVGYLOAD" 
, (case when sra.tripnumbermanual > tripnumberauto 
    then sra.tripnumbermanual*sra.weightrate
    else sra.tripnumberauto*sra.avweight
    end) as weight
from dispatcher.shiftreportsadv sra 
where 
sra.TaskDate between
dispatcher.GetPredefinedTimeFrom ( /*:ParamDataFrom*/ 'за указанный интервал' , 1 , SYSDATE, /*:ParamBeginPeriod*/ to_date('01.'||to_char(
(case when to_char(sysdate,'dd')='01' then
            sysdate-1 
            else sysdate end)
,'mm.yyyy')||' 00:00:00','dd.mm.yyyy hh24:mi:ss')) 
AND dispatcher.GetPredefinedTimeTo ( /*:ParamDataFrom*/ 'за указанный интервал' , 1 , SYSDATE, /*:ParamEndPeriod*/ sysdate);
