
  CREATE OR REPLACE FORCE VIEW "UGH"."V_PLANFACT_PERCENT_SHOV_NOW" ("SHOVID", "TOTAL_PERCENT") AS 
  SELECT t.SHOVID,  round((SUM(VOLUME)/CASE WHEN SUM(PLAN_HOUR_HALF)>0 THEN SUM(PLAN_HOUR_HALF) ELSE 9999999999999999999999.9 END) *100,0)  as total_percent FROM V_PLANFACT_HOURSUM_HALF_SHOV t
 group by t.shovid
;
