
  CREATE OR REPLACE FORCE VIEW "UGH"."V_SHIFTREPORTSADV" ("VEHID", "TASKDATE", "SHIFT", "SHOVID", "UNLOADID", "LOADTYPE", "WORKTYPE", "AVLENGTH", "ROUTELENGTH", "LENGTHMANUAL", "WEIGHTSENSOR", "GPSSENSOR", "TRIPNUMBERAUTO", "TRIPNUMBERMANUAL", "AVWEIGHT", "MAXWEIGHT", "MINWEIGHT", "WEIGHTRATE", "VOLUMERATE", "SPECIFICFUELRATE", "ISEDITED", "ISLASTROUTE", "MASH_SMEN", "AREA", "WORK_TIME_MANUAL", "WORK_TIME_AUTO", "INSERTTIME", "UPDATETIME", "UPDATESNUM", "AVWEIGHTONINSERT", "CUSTOMERNAME", "DANGERLEVEL", "KVDR_CODE", "LOADHEIGHT", "UNLOADHEIGHT", "STOPTIME", "REPAIRTIME", "REPAIR_IS_TO", "UNLOADIDFORLOAD", "ALLLENGTH", "REPORTSHIFT", "REPORTDATE", "AVHEIGHT", "AVGXLOAD", "AVGYLOAD", "WEIGHT") AS 
  select "VEHID","TASKDATE","SHIFT","SHOVID","UNLOADID","LOADTYPE","WORKTYPE","AVLENGTH",
"ROUTELENGTH","LENGTHMANUAL","WEIGHTSENSOR","GPSSENSOR","TRIPNUMBERAUTO",
"TRIPNUMBERMANUAL","AVWEIGHT","MAXWEIGHT","MINWEIGHT","WEIGHTRATE","VOLUMERATE",
"SPECIFICFUELRATE","ISEDITED","ISLASTROUTE","MASH_SMEN","AREA","WORK_TIME_MANUAL",
"WORK_TIME_AUTO","INSERTTIME","UPDATETIME","UPDATESNUM","AVWEIGHTONINSERT",
"CUSTOMERNAME","DANGERLEVEL","KVDR_CODE","LOADHEIGHT","UNLOADHEIGHT","STOPTIME",
"REPAIRTIME","REPAIR_IS_TO","UNLOADIDFORLOAD","ALLLENGTH","REPORTSHIFT","REPORTDATE",
"AVHEIGHT","AVGXLOAD","AVGYLOAD" 
, (case when sra.tripnumbermanual > tripnumberauto 
    then sra.tripnumbermanual*sra.weightrate
    else sra.tripnumberauto*sra.avweight
    end) as weight
from dispatcher.shiftreportsadv sra 
where /*vehid in (select vehid from dispatcher.dumptrucks where isfunctional=1 and ipan<1)
and */
sra.TaskDate = dispatcher.GetCurShiftDate (0, dispatcher.GetPredefinedTimeFrom 
( 'за текущую смену'/*'за предыдущую смену' */, 1 , sysdate ))               
AND sra.Shift = dispatcher.GetCurShiftNum (0, dispatcher.GetPredefinedTimeFrom 
( 'за текущую смену'/*'за предыдущую смену'*/ ,1, sysdate ));
