
  CREATE OR REPLACE FORCE VIEW "UGH"."V_IDLESTOPPAGES_RIGS" ("VEHID", "TIMESTOP", "TIMEGO", "IDLESTOPTYPE", "IDLESTOPTYPEAUTO", "STOPPAGE_NAME", "STOPPAGE_TIME", "COLOR") AS 
  SELECT 
"VEHID","TIMESTOP","TIMEGO","IDLESTOPTYPE","IDLESTOPTYPEAUTO","STOPPAGE_NAME","STOPPAGE_TIME","COLOR"       
FROM
ugh.v_idlestoppages_rigs@rigs;
