
  CREATE OR REPLACE FORCE VIEW "UGH"."V_RIGS_VALUE_UGH" ("DATESHIFT", "WORKTYPE", "VALUE_FACT_M", "VALUE_FACT_HOLE", "RIGNAME", "BLOCK_NAME", "ENTERPRISENAME", "DIVISIONNAME") AS 
  SELECT 
    "DATESHIFT","WORKTYPE","VALUE_FACT_M","VALUE_FACT_HOLE","RIGNAME","BLOCK_NAME","ENTERPRISENAME","DIVISIONNAME"
FROM V_RIGS_VALUE
where enterprisename like '%”гахан%';
